### PR TITLE
B5 medley

### PR DESCRIPTION
**Pull request by vinniefalco**
* fail_file also fails on reads
* Fix bug in rekey where an error code wasn't checked
* Increase coverage
* Add buffer unit test
* Add is_File concept and checks
* Update documentation
* Add example program
* Demote exceptions to asserts in gentex
* Improved commit process
* Dynamic block size in custom allocator

---
This change is [Reviewable](https://reviewable.io/reviews/vinniefalco/nudb/35)

Reviewers: @mellery451 @JoelKatz @bachase 

HTML docs link: http://vinniefalco.github.io/nudb

### CODE REVIEW

**Comment by vinniefalco** [comment]
:lgtm:

**Comment by mellery451** [comment]
Reviewed 53 of 54 files at r1, 5 of 5 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[bench/bench.cpp, line 142 \[r3\]](https://reviewable.io:443/reviews/vinniefalco/nudb/35#-KRAMcTuxJtFQa2IbdUR:-KRAMcTvLuDi3-WSn0EV:bpsfp3j) ([raw file](https://github.com/vinniefalco/nudb/blob/97e8c81b691c6e98dc0f05bc191bf00fa2b1167c/bench/bench.cpp#L142)):*
> ```cpp
>     Fetcher&& fetcher,
>     AddSample&& add_sample,
>     PreFetchHook&& pre_fetch_hook,
> ```

I don't know enough about this, but I wonder if pre_fetch_hook is always useful/needed - if not, could a default noop() be provided here?

---

*[bench/bench.cpp, line 427 \[r3\]](https://reviewable.io:443/reviews/vinniefalco/nudb/35#-KRAQ06jixVRKw7yejtr:-KRAQ06jixVRKw7yejts:bkaz9pw) ([raw file](https://github.com/vinniefalco/nudb/blob/97e8c81b691c6e98dc0f05bc191bf00fa2b1167c/bench/bench.cpp#L427)):*
> ```cpp
>     bench_progress progress(derr, total_ops);
> 
>     enum
> ```

do we prefer `enum class` ?

---

*[bench/bench.cpp, line 445 \[r3\]](https://reviewable.io:443/reviews/vinniefalco/nudb/35#-KRAOwbE5yiGFPJiwp9z:-KRAOwbE5yiGFPJiwpA-:b-6rnf34) ([raw file](https://github.com/vinniefalco/nudb/blob/97e8c81b691c6e98dc0f05bc191bf00fa2b1167c/bench/bench.cpp#L445)):*
> ```cpp
>     // Reserve up front to database that run later don't have less memory
>     for (int i = 0; i < db_last; ++i)
>         for (int j = 0; i < db_last; ++i)
> ```

should these be all `j`s here - or are you doing something tricky that I'm missing? If it is the simple inner index, then I guess compare against `op_last` would make sense too..

---

*[bench/bench.cpp, line 482 \[r3\]](https://reviewable.io:443/reviews/vinniefalco/nudb/35#-KRAPimfNmwzKBBDG4Xl:-KRAPimgAHlRcrVcLcwl:b-o7k0r4) ([raw file](https://github.com/vinniefalco/nudb/blob/97e8c81b691c6e98dc0f05bc191bf00fa2b1167c/bench/bench.cpp#L482)):*
> ```cpp
>     auto const iter_w = 15;
> 
>     for(int op_idx=0;op_idx<op_last;++op_idx)
> ```

minor nit: space after semicolons?

---

*[bench/bench.cpp, line 504 \[r3\]](https://reviewable.io:443/reviews/vinniefalco/nudb/35#-KRAQbdBmH3K8HuZjvMA:-KRAQbdBmH3K8HuZjvMB:b-ygvcz1) ([raw file](https://github.com/vinniefalco/nudb/blob/97e8c81b691c6e98dc0f05bc191bf00fa2b1167c/bench/bench.cpp#L504)):*
> ```cpp
>         auto const min_sample = [&ops_per_sec]{
>             for (auto i = 0; i < db_last; ++i)
>                 if (!ops_per_sec[i][op_fetch].empty())
> ```

it's not obvious to me why `min_sample` only considers `op_fetch` while `max_sample` considers the full matrix.

---

*[include/nudb/impl/rekey.ipp, line 41 \[r3\]](https://reviewable.io:443/reviews/vinniefalco/nudb/35#-KRAbhoL2qKs8LDEL9Ql:-KRAbhoL2qKs8LDEL9Qm:bamaubx) ([raw file](https://github.com/vinniefalco/nudb/blob/97e8c81b691c6e98dc0f05bc191bf00fa2b1167c/include/nudb/impl/rekey.ipp#L41)):*
> ```cpp
> {
>     static_assert(is_File<File>::value,
>         "File requiremnts not met");
> ```

typo - probably search/replace this particular typo

---

*[include/nudb/impl/verify.ipp, line 43 \[r3\]](https://reviewable.io:443/reviews/vinniefalco/nudb/35#-KRAbbDxrxrlO-ekecT_:-KRAbbDxrxrlO-ekecTa:b-c35zko) ([raw file](https://github.com/vinniefalco/nudb/blob/97e8c81b691c6e98dc0f05bc191bf00fa2b1167c/include/nudb/impl/verify.ipp#L43)):*
> ```cpp
> {
>     static_assert(is_File<File>::value,
>         "File requiremnts not met");
> ```

typo (requirements)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vinniefalco/nudb/35)*

**Comment by mellery451** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vinniefalco/nudb/35#-:-KRAcjgtdzy0OMqvqkOg:bnfp4nl)*

**Comment by vinniefalco** [comment]
@mellery451 ugh..

**Comment by vinniefalco** [comment]
Review status: 54 of 59 files reviewed at latest revision, 7 unresolved discussions.

---

*[bench/bench.cpp, line 427 \[r3\]](https://reviewable.io:443/reviews/vinniefalco/nudb/35#-KRAQ06jixVRKw7yejtr:-KRAiyzfi-BojfkHS1Vr:bjz7cgh) ([raw file](https://github.com/vinniefalco/nudb/blob/97e8c81b691c6e98dc0f05bc191bf00fa2b1167c/bench/bench.cpp#L427)):*
<details><summary><i>Previously, mellery451 (Michael Ellery) wrote…</i></summary>
> do we prefer `enum class` ?
</details>
For an in-function enum, in a benchmark program, not part of public API... I don't think I'm going to get too worked up about it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vinniefalco/nudb/35)*

**Comment by vinniefalco** [comment]
Review status: 54 of 59 files reviewed at latest revision, 6 unresolved discussions.

---

*[bench/bench.cpp, line 445 \[r3\]](https://reviewable.io:443/reviews/vinniefalco/nudb/35#-KRAOwbE5yiGFPJiwp9z:-KRAk4cELQoFKqHVV41F:b-xrmydf) ([raw file](https://github.com/vinniefalco/nudb/blob/97e8c81b691c6e98dc0f05bc191bf00fa2b1167c/bench/bench.cpp#L445)):*
<details><summary><i>Previously, mellery451 (Michael Ellery) wrote…</i></summary>
> should these be all `j`s here - or are you doing something tricky that I'm missing? If it is the simple inner index, then I guess compare against `op_last` would make sense too..
</details>
Looks like a bug

---

*[include/nudb/impl/rekey.ipp, line 41 \[r3\]](https://reviewable.io:443/reviews/vinniefalco/nudb/35#-KRAbhoL2qKs8LDEL9Ql:-KRAkAOMu0vYmlV1Wu7n:b-896fix) ([raw file](https://github.com/vinniefalco/nudb/blob/97e8c81b691c6e98dc0f05bc191bf00fa2b1167c/include/nudb/impl/rekey.ipp#L41)):*
<details><summary><i>Previously, mellery451 (Michael Ellery) wrote…</i></summary>
> typo - probably search/replace this particular typo
</details>
Done.

---

*[include/nudb/impl/verify.ipp, line 43 \[r3\]](https://reviewable.io:443/reviews/vinniefalco/nudb/35#-KRAbbDxrxrlO-ekecT_:-KRAkDBoVxvuWo3ZtyD7:b-896fix) ([raw file](https://github.com/vinniefalco/nudb/blob/97e8c81b691c6e98dc0f05bc191bf00fa2b1167c/include/nudb/impl/verify.ipp#L43)):*
<details><summary><i>Previously, mellery451 (Michael Ellery) wrote…</i></summary>
> typo (requirements)
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vinniefalco/nudb/35)*

**Comment by seelabs** [comment]
Review status: 54 of 59 files reviewed at latest revision, 5 unresolved discussions.

---

*[bench/bench.cpp, line 142 \[r3\]](https://reviewable.io:443/reviews/vinniefalco/nudb/35#-KRAMcTuxJtFQa2IbdUR:-KRAgpm4SKDmmjXx6iT9:b-ey0fpv) ([raw file](https://github.com/vinniefalco/nudb/blob/97e8c81b691c6e98dc0f05bc191bf00fa2b1167c/bench/bench.cpp#L142)):*
<details><summary><i>Previously, mellery451 (Michael Ellery) wrote…</i></summary>
> I don't know enough about this, but I wonder if pre_fetch_hook is always useful/needed - if not, could a default noop() be provided here?
</details>
It's hard to write a default here because `PreFetchHook` is a template and lambdas have unutterable types. If we make this a `std::function` I could add a default, but since this is a self-contained file I prefer to just leave it as a lambda.

---

*[bench/bench.cpp, line 445 \[r3\]](https://reviewable.io:443/reviews/vinniefalco/nudb/35#-KRAOwbE5yiGFPJiwp9z:-KRAhtCOukfmWXqqF2HA:b-anb5b1) ([raw file](https://github.com/vinniefalco/nudb/blob/97e8c81b691c6e98dc0f05bc191bf00fa2b1167c/bench/bench.cpp#L445)):*
<details><summary><i>Previously, vinniefalco (Vinnie Falco) wrote…</i></summary>
> Looks like a bug
</details>
That's a copy/paste bug. Though it won't effect results, it just didn't reserve the space for all the indexes. Fixed.

---

*[bench/bench.cpp, line 482 \[r3\]](https://reviewable.io:443/reviews/vinniefalco/nudb/35#-KRAPimfNmwzKBBDG4Xl:-KRAi1PefpV3Mo9rbfx3:b-886gsx) ([raw file](https://github.com/vinniefalco/nudb/blob/97e8c81b691c6e98dc0f05bc191bf00fa2b1167c/bench/bench.cpp#L482)):*
<details><summary><i>Previously, mellery451 (Michael Ellery) wrote…</i></summary>
> minor nit: space after semicolons?
</details>
Fixed

---

*[bench/bench.cpp, line 504 \[r3\]](https://reviewable.io:443/reviews/vinniefalco/nudb/35#-KRAQbdBmH3K8HuZjvMA:-KRAi8httwTZ35sL5BkH:bl5707u) ([raw file](https://github.com/vinniefalco/nudb/blob/97e8c81b691c6e98dc0f05bc191bf00fa2b1167c/bench/bench.cpp#L504)):*
<details><summary><i>Previously, mellery451 (Michael Ellery) wrote…</i></summary>
> it's not obvious to me why `min_sample` only considers `op_fetch` while `max_sample` considers the full matrix.
</details>
Inserts always start with a database with zero items, I skip that because `fetch` will not have a sample at zero. However, this can be simplified to just use the batch_size. Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vinniefalco/nudb/35)*

**Comment by mellery451** [comment]
Reviewed 6 of 6 files at r4.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vinniefalco/nudb/35)*

**Comment by bachase** [comment]
Reviewed 48 of 54 files at r1, 5 of 5 files at r2, 1 of 1 files at r3, 6 of 6 files at r4, 1 of 1 files at r5.
Review status: 55 of 59 files reviewed at latest revision, 8 unresolved discussions.

---

*[bench/bench.cpp, line 258 \[r3\]](https://reviewable.io:443/reviews/vinniefalco/nudb/35#-KRAV-f4FmbkEMANCmti:-KRAV-f4FmbkEMANCmtj:b-uamlk8) ([raw file](https://github.com/vinniefalco/nudb/blob/97e8c81b691c6e98dc0f05bc191bf00fa2b1167c/bench/bench.cpp#L258)):*
> ```cpp
>         auto pre_fetch_hook = [&ts, &ec]() {
>             // Open the close the db so the commit thread does not confound the
>             // timings
> ```

Typo in the comment?  Should it read `Close then open the db`?

---

*[doc/master.qbk, line 215 \[r3\]](https://reviewable.io:443/reviews/vinniefalco/nudb/35#-KRAXCq3XThZNPii2YG3:-KRAXCq3XThZNPii2YG4:b3ki7gm) ([raw file](https://github.com/vinniefalco/nudb/blob/97e8c81b691c6e98dc0f05bc191bf00fa2b1167c/doc/master.qbk#L215)):*
> ```
> The application-defined constant is a 64-bit unsigned integer which the
> caller may set to any value. This value can be retrieved on an open database,
> where it wil lbe equal to the value used at creation time. This constant can
> ```

typo, `wil lbe` 

---

*[include/nudb/verify.hpp, line 31 \[r5\]](https://reviewable.io:443/reviews/vinniefalco/nudb/35#-KRBK2aEYOaBgyFtlUZY:-KRBK2aEYOaBgyFtlUZZ:b-j1yu08) ([raw file](https://github.com/vinniefalco/nudb/blob/e24ef6026f303dfef3fd9ec3c5c0483bf5d99ea7/include/nudb/verify.hpp#L31)):*
> ```cpp
>         @li @b 1 Fast algorith
>     */
>     int algorithm;                      // 0 = normal, 1 = fast
> ```

Make an enum?

---

*[test/buffer.cpp, line 25 \[r5\]](https://reviewable.io:443/reviews/vinniefalco/nudb/35#-KRBM63FMygNrrZzCxg8:-KRBM63FMygNrrZzCxg9:b6e9vn5) ([raw file](https://github.com/vinniefalco/nudb/blob/e24ef6026f303dfef3fd9ec3c5c0483bf5d99ea7/test/buffer.cpp#L25)):*
> ```cpp
>         using buffer = nudb::detail::buffer;
>         static_assert(std::is_default_constructible<buffer>::value, "");
> #if 0
> ```

Buffer requirements are changing?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vinniefalco/nudb/35)*

**Comment by bachase** [comment]
Reviewed 4 of 4 files at r6.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vinniefalco/nudb/35)*

**Comment by nbougalis** [comment]
Review status: 56 of 59 files reviewed at latest revision, 21 unresolved discussions.

---

*[bench/bench.cpp, line 507 \[r5\]](https://reviewable.io:443/reviews/vinniefalco/nudb/35#-KRBN9qeVejQ0eA1-LIz:-KRBN9qfagUKC6VXtvoP:b-4chh94) ([raw file](https://github.com/vinniefalco/nudb/blob/e24ef6026f303dfef3fd9ec3c5c0483bf5d99ea7/bench/bench.cpp#L507)):*
> ```cpp
>             result_dict const& dict, std::uint64_t key) {
>             dout << std::setw(col_w) << std::fixed << std::setprecision(2);
>             // Take the average of all the values, or "NA"" if none collected
> ```

Minor nit: redundant double quote after NA

---

*[bench/bench.cpp, line 521 \[r5\]](https://reviewable.io:443/reviews/vinniefalco/nudb/35#-KRBNTlLTVKD4u9y5K3M:-KRBNTlLTVKD4u9y5K3N:bby0guy) ([raw file](https://github.com/vinniefalco/nudb/blob/e24ef6026f303dfef3fd9ec3c5c0483bf5d99ea7/bench/bench.cpp#L521)):*
> ```cpp
>             }
>         };
>         for (std::uint64_t n = 0; n <= max_sample; n = n ? 10 * n : 10)
> ```

This ternary is really ugly and I'm surprised it doesn't spew warnings.  Is there a point to testing with `n == 0`? Why not start with `1` instead?

---

*[doc/master.qbk, line 214 \[r5\]](https://reviewable.io:443/reviews/vinniefalco/nudb/35#-KRBO2oqnuErVbPsONBv:-KRBO2orgV7k3AOqWmyA:bqi5cj) ([raw file](https://github.com/vinniefalco/nudb/blob/e24ef6026f303dfef3fd9ec3c5c0483bf5d99ea7/doc/master.qbk#L214)):*
> ```
> 
> The application-defined constant is a 64-bit unsigned integer which the
> caller may set to any value. This value can be retrieved on an open database,
> ```

"retrieved *on* an open" -> "retrieved *from* an open"

---

*[include/nudb/basic_store.hpp, line 77 \[r5\]](https://reviewable.io:443/reviews/vinniefalco/nudb/35#-KRBPE3TwI_gTRIeKein:-KRBPE3UmVt2Q4diS48p:b-ykn8at) ([raw file](https://github.com/vinniefalco/nudb/blob/e24ef6026f303dfef3fd9ec3c5c0483bf5d99ea7/include/nudb/basic_store.hpp#L77)):*
> ```cpp
>         std::size_t rate = 0;
>         time_point when = clock_type::now();
>         
> ```

Rogue white space?

---

*[include/nudb/basic_store.hpp, line 156 \[r5\]](https://reviewable.io:443/reviews/vinniefalco/nudb/35#-KRBPMLB4Yyh0nTQ3Jik:-KRBPMLB4Yyh0nTQ3Jil:b-ykn8at) ([raw file](https://github.com/vinniefalco/nudb/blob/e24ef6026f303dfef3fd9ec3c5c0483bf5d99ea7/include/nudb/basic_store.hpp#L156)):*
> ```cpp
> 
>         @par Requirements
>             
> ```

Rogue white space?

---

*[include/nudb/basic_store.hpp, line 160 \[r5\]](https://reviewable.io:443/reviews/vinniefalco/nudb/35#-KRBPPd_qGV0vdXhXzeZ:-KRBPPd_qGV0vdXhXze_:b-ykn8at) ([raw file](https://github.com/vinniefalco/nudb/blob/e24ef6026f303dfef3fd9ec3c5c0483bf5d99ea7/include/nudb/basic_store.hpp#L160)):*
> ```cpp
> 
>         @par Thread safety
>             
> ```

Rogue white space?

---

*[include/nudb/posix_file.hpp, line 117 \[r5\]](https://reviewable.io:443/reviews/vinniefalco/nudb/35#-KRBPp50DFkODI2AT7t8:-KRBPp517w7uBn70VySr:bfdnk36) ([raw file](https://github.com/vinniefalco/nudb/blob/e24ef6026f303dfef3fd9ec3c5c0483bf5d99ea7/include/nudb/posix_file.hpp#L117)):*
> ```cpp
>     /** Remove a file from the file system.
> 
>         It is not an error to attempt erasing a file that does not exist.
> ```

"to attempt *erasing*" -> "to attempt *to erase*"

---

*[include/nudb/win32_file.hpp, line 135 \[r5\]](https://reviewable.io:443/reviews/vinniefalco/nudb/35#-KRBQ__bCr_ZQbHryd2l:-KRBQ__bCr_ZQbHryd2m:bfdnk36) ([raw file](https://github.com/vinniefalco/nudb/blob/e24ef6026f303dfef3fd9ec3c5c0483bf5d99ea7/include/nudb/win32_file.hpp#L135)):*
> ```cpp
>     /** Remove a file from the file system.
> 
>         It is not an error to attempt erasing a file that does not exist.
> ```

"to attempt *erasing*" -> "to attempt *to erase*"

---

*[include/nudb/detail/arena.hpp, line 136 \[r5\]](https://reviewable.io:443/reviews/vinniefalco/nudb/35#-KRBR2FRLxu9o4QAOgHC:-KRBR2FRLxu9o4QAOgHD:b-82kdsm) ([raw file](https://github.com/vinniefalco/nudb/blob/e24ef6026f303dfef3fd9ec3c5c0483bf5d99ea7/include/nudb/detail/arena.hpp#L136)):*
> ```cpp
>         return nullptr;
>     auto const p = const_cast<std::uint8_t*>(
>         reinterpret_cast<uint8_t const*>(this + 1)
> ```

Why do the `const_cast` dance here? It doesn't seem needed: `alloc` isn't `const` so, `this` isn't either. Why not simply: `auto p = reinterpret_cast<uint8_t*>(this + 1) + used_;`

---

*[include/nudb/detail/cache.hpp, line 80 \[r5\]](https://reviewable.io:443/reviews/vinniefalco/nudb/35#-KRBTR57uojVhE1VDmEe:-KRBTR57uojVhE1VDmEf:bo37nno) ([raw file](https://github.com/vinniefalco/nudb/blob/e24ef6026f303dfef3fd9ec3c5c0483bf5d99ea7/include/nudb/detail/cache.hpp#L80)):*
> ```cpp
>     // Constructs a cache that will never have inserts
>     cache_t() = default;
>     
> ```

Rogue white space

---

*[include/nudb/impl/basic_store.ipp, line 18 \[r5\]](https://reviewable.io:443/reviews/vinniefalco/nudb/35#-KRBSPOfhHlmRaSMW2Hw:-KRBSPOfhHlmRaSMW2Hx:bf5fai2) ([raw file](https://github.com/vinniefalco/nudb/blob/e24ef6026f303dfef3fd9ec3c5c0483bf5d99ea7/include/nudb/impl/basic_store.ipp#L18)):*
This is strictly unnecessary: per §16.1 ¶4 of the C++ standard:

> After all replacements due to macro expansion and the defined unary operator have been performed, all remaining identifiers and keywords, except for `true` and `false`, are replaced with the pp-number 0

---

*[include/nudb/impl/basic_store.ipp, line 568 \[r5\]](https://reviewable.io:443/reviews/vinniefalco/nudb/35#-KRBUILBk3EovQERLSsZ:-KRBUILBk3EovQERLSs_:bopgdjm) ([raw file](https://github.com/vinniefalco/nudb/blob/e24ef6026f303dfef3fd9ec3c5c0483bf5d99ea7/include/nudb/impl/basic_store.ipp#L568)):*
> ```cpp
>     cache c0(s_->kh.key_size, s_->kh.block_size, "c0");
>     cache c1(s_->kh.key_size, s_->kh.block_size, "c1");
>     // 0.63212 ~= 1 - 1/e
> ```

Interesting fact. Cryptic comment.

---

*[include/nudb/impl/basic_store.ipp, line 668 \[r5\]](https://reviewable.io:443/reviews/vinniefalco/nudb/35#-KRBJu_262JMfaA8Vm_I:-KRBJu_262JMfaA8Vm_J:b-lxj91s) ([raw file](https://github.com/vinniefalco/nudb/blob/e24ef6026f303dfef3fd9ec3c5c0483bf5d99ea7/include/nudb/impl/basic_store.ipp#L668)):*
> ```cpp
>     // This might be slightly better than the old
>     // view since there could be fewer spills.
>     m.lock();
> ```

FYI: If any of the operations below `throw` then `m` will stay locked. I haven't verified whether they do or not.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vinniefalco/nudb/35)*

**Comment by nbougalis** [comment]
Reviewed 47 of 54 files at r1, 4 of 5 files at r2, 1 of 1 files at r3, 6 of 6 files at r4, 1 of 1 files at r5.
Review status: 56 of 59 files reviewed at latest revision, 21 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vinniefalco/nudb/35)*

**Comment by seelabs** [comment]
Review status: 56 of 59 files reviewed at latest revision, 21 unresolved discussions.

---

*[bench/bench.cpp, line 521 \[r5\]](https://reviewable.io:443/reviews/vinniefalco/nudb/35#-KRBNTlLTVKD4u9y5K3M:-KRBVpYXAMPszMEn_l2w:bm5fenc) ([raw file](https://github.com/vinniefalco/nudb/blob/e24ef6026f303dfef3fd9ec3c5c0483bf5d99ea7/bench/bench.cpp#L521)):*
<details><summary><i>Previously, nbougalis (Nik Bougalis) wrote…</i></summary>
> This ternary is really ugly and I'm surprised it doesn't spew warnings.  Is there a point to testing with `n == 0`? Why not start with `1` instead?
</details>
I used to report the timing for inserting the initial batch into the zero-size database. When I took that out I missed changing the loop bounds. Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vinniefalco/nudb/35)*

**Comment by nbougalis** [comment]
Review status: 55 of 59 files reviewed at latest revision, 21 unresolved discussions.

---

*[bench/bench.cpp, line 521 \[r5\]](https://reviewable.io:443/reviews/vinniefalco/nudb/35#-KRBNTlLTVKD4u9y5K3M:-KRBeerhKyuhutHfCxj3:b-jjp714) ([raw file](https://github.com/vinniefalco/nudb/blob/e24ef6026f303dfef3fd9ec3c5c0483bf5d99ea7/bench/bench.cpp#L521)):*
<details><summary><i>Previously, seelabs (Scott Determan) wrote…</i></summary>
> I used to report the timing for inserting the initial batch into the zero-size database. When I took that out I missed changing the loop bounds. Fixed.
</details>
I notice that `n` now starts from `100`. I suspect that's what you want, but just want to make sure.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vinniefalco/nudb/35)*

**Comment by vinniefalco** [comment]
Review status: 55 of 59 files reviewed at latest revision, 20 unresolved discussions.

---

*[include/nudb/basic_store.hpp, line 77 \[r5\]](https://reviewable.io:443/reviews/vinniefalco/nudb/35#-KRBPE3TwI_gTRIeKein:-KRDww00jzV2Q5-o2IFS:b-grl2pi) ([raw file](https://github.com/vinniefalco/nudb/blob/e24ef6026f303dfef3fd9ec3c5c0483bf5d99ea7/include/nudb/basic_store.hpp#L77)):*
<details><summary><i>Previously, nbougalis (Nik Bougalis) wrote…</i></summary>
> Rogue white space?
</details>
No idea what you're going on about

---

*[include/nudb/verify.hpp, line 31 \[r5\]](https://reviewable.io:443/reviews/vinniefalco/nudb/35#-KRBK2aEYOaBgyFtlUZY:-KRDx6-37CoAooise5x4:b5hnmu) ([raw file](https://github.com/vinniefalco/nudb/blob/e24ef6026f303dfef3fd9ec3c5c0483bf5d99ea7/include/nudb/verify.hpp#L31)):*
<details><summary><i>Previously, bachase (Brad Chase) wrote…</i></summary>
> Make an enum?
</details>
I could make it an `enum` but I don't want to draw that much attention to this member.

---

*[include/nudb/detail/arena.hpp, line 136 \[r5\]](https://reviewable.io:443/reviews/vinniefalco/nudb/35#-KRBR2FRLxu9o4QAOgHC:-KRDxI3pijU48R3Bz359:b-9r9ilk) ([raw file](https://github.com/vinniefalco/nudb/blob/e24ef6026f303dfef3fd9ec3c5c0483bf5d99ea7/include/nudb/detail/arena.hpp#L136)):*
<details><summary><i>Previously, nbougalis (Nik Bougalis) wrote…</i></summary>
> Why do the `const_cast` dance here? It doesn't seem needed: `alloc` isn't `const` so, `this` isn't either. Why not simply: `auto p = reinterpret_cast<uint8_t*>(this + 1) + used_;`
</details>
It was required to compile on all our targets. Maybe that's changed. But I don't know that I want to risk breaking it.

---

*[include/nudb/impl/basic_store.ipp, line 18 \[r5\]](https://reviewable.io:443/reviews/vinniefalco/nudb/35#-KRBSPOfhHlmRaSMW2Hw:-KRDxOXA1N6usRCRGJcQ:bjha4rm) ([raw file](https://github.com/vinniefalco/nudb/blob/e24ef6026f303dfef3fd9ec3c5c0483bf5d99ea7/include/nudb/impl/basic_store.ipp#L18)):*
<details><summary><i>Previously, nbougalis (Nik Bougalis) wrote…</i></summary>
> This is strictly unnecessary: per §16.1 ¶4 of the C++ standard:
> 
> > After all replacements due to macro expansion and the defined unary operator have been performed, all remaining identifiers and keywords, except for `true` and `false`, are replaced with the pp-number 0
</details>
That is true, but this define serves two purposes: to illustrate to the reader that its meant to be changed, and to provide a place where someone can edit the value and easily make it 1 or 0 without deleting the line.

---

*[include/nudb/impl/basic_store.ipp, line 568 \[r5\]](https://reviewable.io:443/reviews/vinniefalco/nudb/35#-KRBUILBk3EovQERLSsZ:-KRDxcETCMa9zQUgVqIw:b5y1nq6) ([raw file](https://github.com/vinniefalco/nudb/blob/e24ef6026f303dfef3fd9ec3c5c0483bf5d99ea7/include/nudb/impl/basic_store.ipp#L568)):*
<details><summary><i>Previously, nbougalis (Nik Bougalis) wrote…</i></summary>
> Interesting fact. Cryptic comment.
</details>
I'm open to suggested wording but I'm not sure that it matters. The exact number is not so important, only that it is less than one and more than 0.5.

---

*[include/nudb/impl/basic_store.ipp, line 668 \[r5\]](https://reviewable.io:443/reviews/vinniefalco/nudb/35#-KRBJu_262JMfaA8Vm_I:-KRDxkXj58ZZ7bYKb3Yo:btdf42p) ([raw file](https://github.com/vinniefalco/nudb/blob/e24ef6026f303dfef3fd9ec3c5c0483bf5d99ea7/include/nudb/impl/basic_store.ipp#L668)):*
<details><summary><i>Previously, nbougalis (Nik Bougalis) wrote…</i></summary>
> FYI: If any of the operations below `throw` then `m` will stay locked. I haven't verified whether they do or not.
</details>
That's fine, nothing is allowed to throw. Even so, the caller provides `m` which goes out of scope on a stack unwinding so we're good.

---

*[test/buffer.cpp, line 25 \[r5\]](https://reviewable.io:443/reviews/vinniefalco/nudb/35#-KRBM63FMygNrrZzCxg8:-KRDxrQEBwyfRHQtxLj6:b-61w3di) ([raw file](https://github.com/vinniefalco/nudb/blob/e24ef6026f303dfef3fd9ec3c5c0483bf5d99ea7/test/buffer.cpp#L25)):*
<details><summary><i>Previously, bachase (Brad Chase) wrote…</i></summary>
> Buffer requirements are changing?
</details>
Eventually I would like to elevate `buffer` to a public interface. This commented out code serves as a reminder.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vinniefalco/nudb/35)*

**Comment by bachase** [comment]
OK

---

Reviewed 1 of 1 files at r7, 4 of 4 files at r8, 3 of 3 files at r9.
Review status: all files reviewed at latest revision, 16 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vinniefalco/nudb/35#-:-KRT_xvQWuca2Sl-kJvv:b2nhksp)*

**Comment by vinniefalco** [comment]
Review status: 58 of 59 files reviewed at latest revision, 16 unresolved discussions.

---

*[bench/bench.cpp, line 258 at r3](https://reviewable.io:443/reviews/vinniefalco/nudb/35#-KRAV-f4FmbkEMANCmti:-KRDyKVAg6bEwoM_9g8N:b-896fix) ([raw file](https://github.com/vinniefalco/nudb/blob/97e8c81b691c6e98dc0f05bc191bf00fa2b1167c/bench/bench.cpp#L258)):*
<details><summary><i>Previously, bachase (Brad Chase) wrote…</i></summary>
> Typo in the comment?  Should it read `Close then open the db`?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vinniefalco/nudb/35)*

**Comment by vinniefalco** [comment]
Review status: 58 of 59 files reviewed at latest revision, 16 unresolved discussions.

---

*[include/nudb/posix_file.hpp, line 117 at r5](https://reviewable.io:443/reviews/vinniefalco/nudb/35#-KRBPp50DFkODI2AT7t8:-KRTdKw9QRVrueycGE1c:b-896fix) ([raw file](https://github.com/vinniefalco/nudb/blob/e24ef6026f303dfef3fd9ec3c5c0483bf5d99ea7/include/nudb/posix_file.hpp#L117)):*
<details><summary><i>Previously, nbougalis (Nik Bougalis) wrote…</i></summary>
> "to attempt *erasing*" -> "to attempt *to erase*"
</details>
Done.

---

*[include/nudb/verify.hpp, line 31 at r5](https://reviewable.io:443/reviews/vinniefalco/nudb/35#-KRBK2aEYOaBgyFtlUZY:-KRTdvfDyJOt_b1gJORc:b-896fix) ([raw file](https://github.com/vinniefalco/nudb/blob/e24ef6026f303dfef3fd9ec3c5c0483bf5d99ea7/include/nudb/verify.hpp#L31)):*
<details><summary><i>Previously, vinniefalco (Vinnie Falco) wrote…</i></summary>
> I could make it an `enum` but I don't want to draw that much attention to this member.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vinniefalco/nudb/35)*

**Comment by vinniefalco** [comment]
All of the current comments have been addressed, is this ready to merge?

**Comment by vinniefalco** [comment]
Review status: 58 of 59 files reviewed at latest revision, 10 unresolved discussions.

---

*[doc/master.qbk, line 215 at r3](https://reviewable.io:443/reviews/vinniefalco/nudb/35#-KRAXCq3XThZNPii2YG3:-KRVF4Pmnk2CY6zvUyHZ:b-896fix) ([raw file](https://github.com/vinniefalco/nudb/blob/97e8c81b691c6e98dc0f05bc191bf00fa2b1167c/doc/master.qbk#L215)):*
<details><summary><i>Previously, bachase (Brad Chase) wrote…</i></summary>
> typo, `wil lbe` 
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vinniefalco/nudb/35)*

**Comment by JoelKatz** [comment]
:neckbeard::+1:

**Pull request closed without merging**
