### PR TITLE
Odds and Ends

### PR DESCRIPTION
**Pull request by vinniefalco**
* Fix doc typos
* Improve file creation on POSIX

### CODE REVIEW

**Comment by miguelportilla** [comment]
👍

**Comment by vinniefalco** [comment]
So why did code coverage go down?

**Comment by ximinez** [comment]
Because math is unforgiving. According to codecov, you removed 8 lines, all of which were covered. 
```
Before: 1661 hits / 1719 total ~= 0.966259
 After: 1653 hits / 1711 total ~= 0.966102
Difference:                       0.000157
```

**Comment by vinniefalco** [comment]
wtf....

**Comment by ximinez** [comment]
More generally, with `x` being hits and `y` being total lines, removing 8 covered lines gives:
```
Before: x/y
 After: (x-8)/(y-8)
Difference:
x/y - (x-8)/(y-8)
== ( x(y-8) - y(x-8) ) / y(y-8)
== ( xy - 8x - xy + 8y ) / y(y-8)
== ( 8y - 8x ) / y(y-8)
```
Since `y > x`, this result will always be positive, so before will always be larger than after.

**Comment by vinniefalco** [comment]
Congratulations, you have stumbled upon the formula for increasing code coverage arbitrarily.

**Comment by vinniefalco** [comment]
@ximinez This brings up an interesting point, if a change only removes covered lines, should it ever be considered as "failing" the compilation/code coverage checks? I would think not.

**Comment by ximinez** [comment]
@vinniefalco I would say it should not. Codecov is a lot more sensible about it if you notice that codecov/project has the green check, but the message is
> Absolute coverage decreased by -0.01% but relative coverage increased by +3.37% compared to 00adc6a
(Though I don't know how it's measuring relative coverage.)

**Pull request merged**
